config/routes.rb
Facelist::Application.routes.draw do

  devise_for :users
resources :people

  get "home/index"

  root :to => "home#index"

end

app/models/person.rb
class Person < ActiveRecord::Base
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  validates_attachment :photo, :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] }


  validates :name,  :presence => true
  validates :email, :presence => true,
            :length => { :minimum => 6 }
  validates :phone, :length =>{ :minimum =>10, :maximum =>10}



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# module Api
#   module V1

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

end
# end
# end

app/controllers/home_controller.rb
# module Api
#   module V1
class HomeController < ApplicationController
  def index
  end
end
  # end
  # end

app/controllers/people_controller.rb
# module Api
#   module V1
class PeopleController < ApplicationController
  before_action :authenticate_user!, :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all.order(:name)
    # render json: {message: 'Resource not found'}, status: 404
  end

  # GET /people/1
  # GET /people/1.json
  def show

  end


  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        @person.update_attribute(:photo, params[:person][:photo])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :email, :phone, :photo)
    end
end
  # end
  # end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/home/index.html.erb
<h1>Facelist</h1>
<p>Because sometimes you drank too much. Or you are just bad with faces.</p>
<%= link_to "Get your memory back.", people_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facelist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
    <div class="field">
      <%= f.label :photo %><br>
      <%= f.file_field :photo  %>
         </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/people/edit.html.erb
<h1>Edit Information</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<hr>
<h1 id ="peopleh1">The Amazing People of RTO+P</h1>
<%= image_tag('rtop.png') %>



<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <br/>
<hr>
  <tbody>
    <% @people.each do |person| %>

      <tr>

        <td><%= person.name %></td>
        <td><%= person.email %></td>
        <td><%= person.phone.insert(3, '-').insert(7, '-') %></td>
        <td><%= image_tag person.photo.url(:thumb), :alt => '' %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>




    <% end %>

  </tbody>

</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<div class ="show">

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @person.phone.insert(3, '-').insert(7, '-') %>
</p>

<p>
  <strong>Face:</strong>
  <br/>
  <%= image_tag @person.photo.url %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>
</div>